### ISSUE TITLE
Main tasks： 2 Delete objects

### ISSUE THREAD

**Issue by SahSih** [SahSih/genius#4]
Figure out how to query the objects.

**Comment by lephdao** [comment]
* Implement Delete function to delete: Restaurant, Book, and Tutoring.
* Something is wrong with Restaurant.

**Comment by lephdao** [comment]
* FINISH: Query multiple objects to one page.
* https://howchoo.com/g/yzzkodmzzmj/combine-two-querysets-with-different-models

**Comment by lephdao** [comment]
FINISH: User is able to delete any kind of object in their user page aka user.html
